### PR TITLE
Update to 0.10.3

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
could you please merge.

**Comment by sannykr** [comment]
@vamega: Hi Varun, when I used the sha that I got using my terminal , it didn't work. When I looked at the errors on circleci, it suggested a different sha and that worked.  Can you please tell me why it happened.

**Comment by vamega** [comment]
Hi Sanny.

I'll look at this later today.

Varun Madiath

**Comment by sannykr** [comment]
@vamega : I have made a new recipe and new pull request. That's what admins have suggested. 
https://github.com/conda-forge/conda-forge.github.io/issues/426#issuecomment-321897876

**Comment by vamega** [comment]
Thanks @sannykr  looks like everything is passing now!

**Pull request merged**
